version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-container
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  rabbitmq:
    container_name: rabbitmq-container
    ports:
      - 0.0.0.0:15672:15672/tcp
      - 0.0.0.0:5672:5672/tcp
    expose:
      - 15671/tcp
      - 15672/tcp
      - 15691/tcp
      - 15692/tcp
      - 25672/tcp
      - 4369/tcp
      - 5671/tcp
      - 5672/tcp
    environment:
      - PATH=/opt/rabbitmq/sbin:/opt/erlang/bin:/opt/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ERLANG_INSTALL_PATH_PREFIX=/opt/erlang
      - OPENSSL_INSTALL_PATH_PREFIX=/opt/openssl
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq
      - RABBITMQ_VERSION=3.13.6
      - RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
      - RABBITMQ_HOME=/opt/rabbitmq
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    image: rabbitmq:3.13-management
    command: rabbitmq-server


  mongodb-community-server:
    container_name: mongodb-container
    ports:
      - 0.0.0.0:27017:27017/tcp
    expose:
      - 27017/tcp
    user: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=admin
    image: mongodb/mongodb-community-server:latest

  elasticsearch:
    ports:
      - 0.0.0.0:9200:9200/tcp
    expose:
      - 9200/tcp
      - 9300/tcp
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ELASTIC_CONTAINER=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elastic-container
    command: eswrapper

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
