server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: JakrACIBjpwNEWXDzl5J66RuSaB6DjxzzvbN6DegElTZJgBYxbMjdtGO2DRF3e4vR9VfVNFHlIY78r3/9lAurqb0rA2oJJhhuEgmNMb9LmeTtWiNow5F8r+qBNPGA/AZDnqwoG1BmscAMQjzpTL+LuGGVf406gOSF3mkcWkCijELuAfo6h6/odj6KEk+nd4MZQLj0BkSgD16xgYSVmVRBjYaU8xt74rSjGLARk6HYpwwjd2cwWMhgDE+PMkjSk7Z9KgJCHNzea4HSoeTVeHS96dI18h0leRZBbVD3WS4Ge1iVNCmXPlBx/iS3Ifv9/smprJAzsI63+iLeGbGf6XGH86uTUh1j1jqV1W+Ng82neyC2B77Rp1VnCgK/FvXmdAmq4CJv0HNcMVKKNi9QTPQpODwadU/yBWyBiX5rCVYM7vZFjp9eGpGzRnKCwTmB/2CpPyDsa8sRtJG4DiDWnqLZNswd4aXsmYcjOO/OavzTPnoWSqbrPMHtzYaDlLapMu/K+fMH2IR1Fd1atkmmA7QhjEql1CGlTZf7UMvnAfWJONpqZI2PGuMZdC3UJvGVNhX04DI2/59Inr1jh872Ujqa0fBM2d6KgS/1mbOLFMYFOye7hEPkOkvjYlNC3+pLfezKLmET08MzwpBVGq74KAqgXNUJvBGLoXIultAmDon4iHa59sqfohNoyzxY3g2fJid
